from functions import *
from bfs import *

print("hello world")

# puzzles = loadToArray(loadPuzzles("2x2_01_00002"))
# x,y = setStart(puzzles)
# print(puzzles)
# print(x)
# print(y)
# print(checkpossibilities(puzzles,x,y))
# print("------------")
# switchPositions("U",x,y,puzzles)
# x,y = setStart(puzzles)
# print(puzzles)
# print(x)
# print(y)
# print(checkpossibilities(puzzles,x,y))
# print("------------")
# switchPositions("P",x,y,puzzles)
# x,y = setStart(puzzles)
# print(puzzles)
# print(x)
# print(y)
# print(checkpossibilities(puzzles,x,y))
# print("------------")
# switchPositions("D",x,y,puzzles)
# x,y = setStart(puzzles)
# print(puzzles)
# print(x)
# print(y)
# print(checkpossibilities(puzzles,x,y))
# print("------------")
# switchPositions("L",x,y,puzzles)
# x,y = setStart(puzzles)
# print(puzzles)
# print(x)
# print(y)
# print(checkpossibilities(puzzles,x,y))

puzzles = loadToArray(loadPuzzles("2x2_02_00002"))
puzzlesAnswer = [['1','2'],['3','0']]
print(bfs(puzzles,puzzlesAnswer))